### ISSUE TITLE
test-charpoly fails when ntl is enabled

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/linbox#291]

**Comment by ClementPernet** [comment]
It only happens when using system's (debian) libntl-dev (version 11.4.3-1build1). Seems to be a memory management issue:
```
Thread 1 "test-charpoly" received signal SIGSEGV, Segmentation fault.
0x00007ffff52e076e in NTL::LazyTable<NTL::FFTPrimeInfo, 20000l>::~LazyTable() () from /usr/lib/x86_64-linux-gnu/libntl.so.43
(gdb) where
#0  0x00007ffff52e076e in NTL::LazyTable<NTL::FFTPrimeInfo, 20000l>::~LazyTable() () from /usr/lib/x86_64-linux-gnu/libntl.so.43
#1  0x00007ffff556d15e in __cxa_finalize (d=0x7ffff5522000)
    at cxa_finalize.c:83
#2  0x00007ffff52da1e7 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libntl.so.43
#3  0x00007fffffffdea0 in ?? ()
#4  0x00007ffff7fe0f5b in _dl_fini () at dl-fini.c:138
Backtrace stopped: frame did not save the PC

```
 With self-compiled instances of NTL (tested with v11.3.2 and v11.5.1), the problem no longer occurs.
